platform :ios, '10.3'
inhibit_all_warnings!

use_frameworks!


target 'Caffe2Test' do
  pod 'Caffe2Kit', :path => '../../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
